WINDOW_WIDTH: 400
WINDOW_HEIGHT: 400
WINDOW_WALL_WIDTH: 70
GRID_SPACING: &player_vel 10
FRAMERATE: 10
BACKGROUND_IMG: 'sprites/background.jpg'
MAP: 'myfirstmap'

# Used for collision detection.
PLAYER_WIDTH: 15
PLAYER_HEIGHT: 19

PLAYER_VELOCITY: *player_vel
BIKE_VELOCITY_FACTOR: 1
BIKE_SOUND: 'sounds/bike.wav'
MUSHROOM_SOUND: 'sounds/mushroom.wav'


# HOST = "localhost"
# PORT = 12345
# buffer_size = 2048
# num_players = 5
