WINDOW_WIDTH: 400
WINDOW_HEIGHT: 400
GRID_SPACING: &grid_spacing 10
FRAMERATE: 10

BACKGROUND_IMG: 'sprites/background.jpg'
MAP: 'myfirstmap'

PLAYER_VELOCITY: *grid_spacing
GRASS_SPEED: 6 # The players speed when in grass.
WATER_SPEED: 4 # The players speed when in water.

BIKE_SOUND: 'sounds/bike.wav'
MUSHROOM_SOUND: 'sounds/mushroom.wav'


BUFFER_SIZE : 2048
MAX_CONNECTIONS: 3
